# Generated by Django 5.0.8 on 2026-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Tacos & Antojitos', 'Tacos & Antojitos'), ('Comida Rápida', 'Comida Rápida'), ('Postres dulces', 'Postres dulces'), ('Bebidas frías', 'Bebidas frías'), ('Bebidas Calientes', 'Bebidas Calientes'), ('Saludable', 'Saludable'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría del Platillo'),
        ),
    ]
